# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# User configuration

export EDITOR=nvim
alias ccf='cc -Wall -Wextra -Werror -Wpedantic'
